In [ ]:
from scripts.metrics import MetricsBuilder
from scripts.load_data import DataLoader
import sys
from pathlib import Path

import pandas as pd

ANALYZER_DIR = Path.cwd().parent

# prioridad al analyzer local
sys.path.insert(0, str(ANALYZER_DIR.resolve()))

# limpiar módulos cacheados
for module in list(sys.modules):
    if module == "scripts" or module.startswith("scripts."):
        del sys.modules[module]

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 200)
pd.set_option("display.max_colwidth", 200)

# imports DESPUÉS del sys.path

loader = DataLoader().load_all()

metrics = MetricsBuilder(loader)

In [4]:
repository_risk = (
    metrics.repository_risk()
)

repository_risk.head(30)

normalized_severity,repository,critical_count,high_count,low_count,medium_count,unknown_count,total_vulnerabilities,risk_score
20,trino-packages,12,142,68,138,0,360,830
6,github-actions,3,28,4,37,0,72,177
12,trino-admin,6,24,2,18,0,50,140
11,trino,1,15,4,25,0,45,104
3,aws-proxy,0,11,3,15,0,29,66
10,tempto,3,8,1,13,0,25,66
14,trino-gateway,0,12,1,9,0,22,55
4,benchto,4,6,1,3,0,14,45
17,trino-hive-apache,5,5,1,2,0,13,45
0,539489521a87dff7364bcf49dcb350dcbdebac92,0,0,0,22,0,22,44
19,trino-js-client,0,5,1,11,0,17,38
22,trino-rubix,3,5,2,3,0,13,38
5,docker-images,0,7,1,6,0,14,34
15,trino-go-client,0,5,0,3,0,8,21
18,trino-hive-jdbc,1,2,1,3,0,7,18
21,trino-query-ui,0,0,0,9,0,9,18
7,grafana-trino,1,2,0,0,0,3,11
9,presto-cassandra-server,1,2,0,0,0,3,11
13,trino-coral,0,2,1,1,0,4,9
23,trino-verifier-queries,0,1,0,2,0,3,7
16,trino-hadoop-apache,0,2,1,0,0,3,7
2,ambari-presto-service,0,1,0,1,0,2,5
25,trino-yugabyte-driver,0,0,1,2,0,3,5
24,trino-yarn,0,1,0,0,0,1,3
8,orc-protobuf,0,1,0,0,0,1,3
26,trino.io,0,1,0,0,0,1,3
1,8d2730953f62a400e1feac6a6716a606d6bc2be8,0,0,0,1,0,1,2

In [5]:
repository_risk.sort_values(
    by="risk_score",
    ascending=False,
).head(20)

normalized_severity,repository,critical_count,high_count,low_count,medium_count,unknown_count,total_vulnerabilities,risk_score
20,trino-packages,12,142,68,138,0,360,830
6,github-actions,3,28,4,37,0,72,177
12,trino-admin,6,24,2,18,0,50,140
11,trino,1,15,4,25,0,45,104
3,aws-proxy,0,11,3,15,0,29,66
10,tempto,3,8,1,13,0,25,66
14,trino-gateway,0,12,1,9,0,22,55
4,benchto,4,6,1,3,0,14,45
17,trino-hive-apache,5,5,1,2,0,13,45
0,539489521a87dff7364bcf49dcb350dcbdebac92,0,0,0,22,0,22,44
19,trino-js-client,0,5,1,11,0,17,38
22,trino-rubix,3,5,2,3,0,13,38
5,docker-images,0,7,1,6,0,14,34
15,trino-go-client,0,5,0,3,0,8,21
18,trino-hive-jdbc,1,2,1,3,0,7,18
21,trino-query-ui,0,0,0,9,0,9,18
7,grafana-trino,1,2,0,0,0,3,11
9,presto-cassandra-server,1,2,0,0,0,3,11
13,trino-coral,0,2,1,1,0,4,9
23,trino-verifier-queries,0,1,0,2,0,3,7