In [24]:
import pandas as pd
import numpy as np
from pathlib import Path

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 200)
pd.set_option("display.max_colwidth", 200)

In [36]:
ROOT = Path("../../").resolve()
DATA_DIR = ROOT / "data" / "normalized"

CODEQL_PATH = DATA_DIR / "code_vulnerabilities.parquet"
DEPENDENCIES_PATH = DATA_DIR / "dependencies.parquet"
DEPENDENCY_VULNS_PATH = DATA_DIR / "dependency_vulnerabilities.parquet"
REPOSITORIES_PATH = DATA_DIR / "repositories.parquet"

print(DATA_DIR.resolve())

/workspaces/P1-ciberseguridad/data/normalized

In [37]:
codeql_df = pd.read_parquet(CODEQL_PATH)
dependencies_df = pd.read_parquet(DEPENDENCIES_PATH)
dependency_vulns_df = pd.read_parquet(DEPENDENCY_VULNS_PATH)
repositories_df = pd.read_parquet(REPOSITORIES_PATH)

In [38]:
datasets = {
    "repositories": repositories_df,
    "codeql": codeql_df,
    "dependencies": dependencies_df,
    "dependency_vulnerabilities": dependency_vulns_df,
}

for name, df in datasets.items():
    print("=" * 80)
    print(f"DATASET: {name}")
    print("=" * 80)

    print("\nShape:")
    print(df.shape)

    print("\nColumns:")
    print(df.columns.tolist())

    print("\nDtypes:")
    print(df.dtypes)

    print("\nPreview:")
    display(df.head(3))

================================================================================
DATASET: repositories
================================================================================

Shape:
(46, 7)

Columns:
['repository_id', 'repository_name', 'total_dependencies', 'total_dependency_vulnerabilities', 'total_code_vulnerabilities', 'analyzed_at', 'analysis_status']

Dtypes:
repository_id                         str
repository_name                       str
total_dependencies                  int64
total_dependency_vulnerabilities    int64
total_code_vulnerabilities          int64
analyzed_at                           str
analysis_status                       str
dtype: object

Preview:

,repository_id,repository_name,total_dependencies,total_dependency_vulnerabilities,total_code_vulnerabilities,analyzed_at,analysis_status
0,9991dc2fdc4450f295d3673933856751e7c16bf9,ambari-presto-service,8,2,0,2026-05-07T16:22:15.799748+00:00,completed
1,3e07d4c71e588445c016a7d056d7e15105f9524a,aws-proxy,840,29,0,2026-05-07T16:22:15.799840+00:00,completed
2,72d2d74b93ff1171abcc53e0299a936c62fbe4e4,benchto,76,14,0,2026-05-07T16:22:15.799856+00:00,completed

================================================================================
DATASET: codeql
================================================================================

Shape:
(23, 13)

Columns:
['finding_id', 'repository_id', 'rule_id', 'severity', 'message', 'file_path', 'start_line', 'end_line', 'start_column', 'end_column', 'kind', 'tool', 'analyzed_at']

Dtypes:
finding_id          str
repository_id       str
rule_id             str
severity            str
message             str
file_path           str
start_line        int64
end_line         object
start_column      int64
end_column        int64
kind                str
tool                str
analyzed_at         str
dtype: object

Preview:

,finding_id,repository_id,rule_id,severity,message,file_path,start_line,end_line,start_column,end_column,kind,tool,analyzed_at
0,9c9ba22e313a210942fe744a63f949808f46c004,539489521a87dff7364bcf49dcb350dcbdebac92,js/xss,warning,Cross-site scripting vulnerability due to [user-provided value](1).,reveal/plugin/notes/speaker-view.html,480,None,31,51,notApplicable,codeql,2026-05-07T16:22:15.658658+00:00
1,af850b84b02440e46b1e948a30698ae08ef0b9b8,539489521a87dff7364bcf49dcb350dcbdebac92,js/xss,warning,Cross-site scripting vulnerability due to [user-provided value](1).,reveal/plugin/notes/speaker-view.html,483,None,31,41,notApplicable,codeql,2026-05-07T16:22:15.658688+00:00
2,b918c447dff5913baacdc04210bca45419a2336a,539489521a87dff7364bcf49dcb350dcbdebac92,js/xss,warning,Cross-site scripting vulnerability due to [user-provided value](1).,reveal/plugin/notes/speaker-view.html,542,None,40,50,notApplicable,codeql,2026-05-07T16:22:15.658713+00:00

================================================================================
DATASET: dependencies
================================================================================

Shape:
(7120, 14)

Columns:
['dependency_id', 'repository_id', 'repository_name', 'artifact_name', 'artifact_version', 'artifact_type', 'package_url', 'cpe', 'licenses', 'locations', 'found_by', 'metadata', 'sbom_source', 'analyzed_at']

Dtypes:
dependency_id          str
repository_id          str
repository_name        str
artifact_name          str
artifact_version       str
artifact_type          str
package_url            str
cpe                 object
licenses            object
locations           object
found_by               str
metadata            object
sbom_source            str
analyzed_at            str
dtype: object

Preview:

,dependency_id,repository_id,repository_name,artifact_name,artifact_version,artifact_type,package_url,cpe,licenses,locations,found_by,metadata,sbom_source,analyzed_at
0,56e7fac50f078364bb8d8b64985476565ddcb706,9991dc2fdc4450f295d3673933856751e7c16bf9,ambari-presto-service,mock,1.0.1,python,pkg:pypi/mock@1.0.1,"[{'cpe': 'cpe:2.3:a:python-mock:python-mock:1.0.1:*:*:*:*:*:*:*', 'source': 'syft-generated'}, {'cpe': 'cpe:2.3:a:python-mock:python_mock:1.0.1:*:*:*:*:*:*:*', 'source': 'syft-generated'}, {'cpe':...",[],"[{'path': '/requirements.txt', 'accessPath': '/requirements.txt', 'annotations': {'evidence': 'primary'}}]",python-package-cataloger,"{'name': 'mock', 'versionConstraint': '==1.0.1', 'virtualPath': None, 'pomProperties': None, 'pomProject': None, 'value': None, 'manifest': None, 'digest': None, 'comment': None, 'resolved': None,...",syft,2026-05-07T16:22:13.610587+00:00
1,56e7fac50f078364bb8d8b64985476565ddcb706,9991dc2fdc4450f295d3673933856751e7c16bf9,ambari-presto-service,mock,1.0.1,python,pkg:pypi/mock@1.0.1,"[{'cpe': 'cpe:2.3:a:python-mock:python-mock:1.0.1:*:*:*:*:*:*:*', 'source': 'syft-generated'}, {'cpe': 'cpe:2.3:a:python-mock:python_mock:1.0.1:*:*:*:*:*:*:*', 'source': 'syft-generated'}, {'cpe':...",[],"[{'path': '/setup.py', 'accessPath': '/setup.py', 'annotations': {'evidence': 'primary'}}]",python-package-cataloger,None,syft,2026-05-07T16:22:13.610620+00:00
2,fa57e5cc7dd7ea22fdf977709cda08b68276e66f,9991dc2fdc4450f295d3673933856751e7c16bf9,ambari-presto-service,nose,1.3.7,python,pkg:pypi/nose@1.3.7,"[{'cpe': 'cpe:2.3:a:python-nose:python-nose:1.3.7:*:*:*:*:*:*:*', 'source': 'syft-generated'}, {'cpe': 'cpe:2.3:a:python-nose:python_nose:1.3.7:*:*:*:*:*:*:*', 'source': 'syft-generated'}, {'cpe':...",[],"[{'path': '/requirements.txt', 'accessPath': '/requirements.txt', 'annotations': {'evidence': 'primary'}}]",python-package-cataloger,"{'name': 'nose', 'versionConstraint': '==1.3.7', 'virtualPath': None, 'pomProperties': None, 'pomProject': None, 'value': None, 'manifest': None, 'digest': None, 'comment': None, 'resolved': None,...",syft,2026-05-07T16:22:13.610628+00:00

================================================================================
DATASET: dependency_vulnerabilities
================================================================================

Shape:
(722, 24)

Columns:
['vulnerability_record_id', 'repository_id', 'repository', 'dependency_id', 'package_name', 'package_version', 'package_type', 'language', 'purl', 'location', 'vulnerability_id', 'related_cve', 'severity', 'cvss_score', 'epss', 'risk', 'cwe', 'fix_state', 'fix_versions', 'description', 'data_source', 'namespace', 'tool', 'analyzed_at']

Dtypes:
vulnerability_record_id        str
repository_id                  str
repository                     str
dependency_id                  str
package_name                   str
package_version                str
package_type                   str
language                       str
purl                           str
location                       str
vulnerability_id               str
related_cve                    str
severity                       str
cvss_score                 float64
epss                       float64
risk                       float64
cwe                         object
fix_state                      str
fix_versions                object
description                    str
data_source                    str
namespace                      str
tool                           str
analyzed_at                    str
dtype: object

Preview:

,vulnerability_record_id,repository_id,repository,dependency_id,package_name,package_version,package_type,language,purl,location,vulnerability_id,related_cve,severity,cvss_score,epss,risk,cwe,fix_state,fix_versions,description,data_source,namespace,tool,analyzed_at
0,b14d7c0940e22a35b43c46ab40c322db76044c8b,9991dc2fdc4450f295d3673933856751e7c16bf9,ambari-presto-service,c8478ce28dd44e584e619a5f594c3d62d71dfe86,virtualenv,12.0.7,python,python,pkg:pypi/virtualenv@12.0.7,/requirements.txt,GHSA-rqc4-2hc7-8c8v,CVE-2024-53899,High,8.4,0.00226,0.17967,"[CWE-77, CWE-78]",fixed,[20.26.6],virtualenv allows command injection through activation scripts for a virtual environment,https://github.com/advisories/GHSA-rqc4-2hc7-8c8v,github:language:python,grype,2026-05-07T16:22:15.071615+00:00
1,96b3f15b87a70d57873a7ad495a74171321f5ace,9991dc2fdc4450f295d3673933856751e7c16bf9,ambari-presto-service,c8478ce28dd44e584e619a5f594c3d62d71dfe86,virtualenv,12.0.7,python,python,pkg:pypi/virtualenv@12.0.7,/requirements.txt,GHSA-597g-3phw-6986,CVE-2026-22702,Medium,4.5,0.00014,0.00665,"[CWE-59, CWE-362]",fixed,[20.36.1],virtualenv Has TOCTOU Vulnerabilities in Directory Creation,https://github.com/advisories/GHSA-597g-3phw-6986,github:language:python,grype,2026-05-07T16:22:15.071683+00:00
2,7afc9c4cc199b51456e5804929b3dade71de4507,3e07d4c71e588445c016a7d056d7e15105f9524a,aws-proxy,96d52bd1d72b17eeaf560d27d0cf2e9ff47b4df4,netty-handler,4.1.100.Final,java-archive,java,pkg:maven/io.netty/netty-handler@4.1.100.Final,/trino-aws-proxy/target/test-jars/bundle-2.24.6.jar,GHSA-4g8c-wm8x-jfhw,CVE-2025-24970,High,7.5,0.00953,0.71475,[CWE-20],fixed,[4.1.118.Final],SslHandler doesn't correctly validate packets which can lead to native crash when using native SSLEngine,https://github.com/advisories/GHSA-4g8c-wm8x-jfhw,github:language:java,grype,2026-05-07T16:22:15.087269+00:00

In [39]:
print("=" * 80)
print("BASIC COUNTS")
print("=" * 80)

print(f"Repositories: {len(repositories_df):,}")

if "repository" in codeql_df.columns:
    print(
        f"Repositories with CodeQL findings: {codeql_df['repository'].nunique():,}")

print(f"CodeQL findings: {len(codeql_df):,}")

if "package" in dependencies_df.columns:
    print(f"Unique packages: {dependencies_df['package'].nunique():,}")

if "vulnerability_id" in dependency_vulns_df.columns:
    print(
        f"Unique CVEs: {dependency_vulns_df['vulnerability_id'].nunique():,}")

print(f"Dependency vulnerabilities: {len(dependency_vulns_df):,}")

================================================================================
BASIC COUNTS
================================================================================
Repositories: 46
CodeQL findings: 23
Unique CVEs: 272
Dependency vulnerabilities: 722

In [40]:
def analyze_nulls(df, name):
    print("=" * 80)
    print(f"NULL ANALYSIS: {name}")
    print("=" * 80)

    nulls = df.isnull().sum()
    null_percentage = (nulls / len(df)) * 100

    result = pd.DataFrame({
        "null_count": nulls,
        "null_percentage": null_percentage
    })

    result = result.sort_values(
        by="null_percentage",
        ascending=False
    )

    display(result)


for name, df in datasets.items():
    analyze_nulls(df, name)

================================================================================
NULL ANALYSIS: repositories
================================================================================

                                  null_count  null_percentage
repository_id                              0              0.0
repository_name                            0              0.0
total_dependencies                         0              0.0
total_dependency_vulnerabilities           0              0.0
total_code_vulnerabilities                 0              0.0
analyzed_at                                0              0.0
analysis_status                            0              0.0

================================================================================
NULL ANALYSIS: codeql
================================================================================

               null_count  null_percentage
end_line               23            100.0
repository_id           0              0.0
rule_id                 0              0.0
severity                0              0.0
finding_id              0              0.0
message                 0              0.0
file_path               0              0.0
start_line              0              0.0
start_column            0              0.0
end_column              0              0.0
kind                    0              0.0
tool                    0              0.0
analyzed_at             0              0.0

================================================================================
NULL ANALYSIS: dependencies
================================================================================

                  null_count  null_percentage
metadata                  92         1.292135
dependency_id              0         0.000000
repository_name            0         0.000000
artifact_name              0         0.000000
artifact_version           0         0.000000
repository_id              0         0.000000
artifact_type              0         0.000000
package_url                0         0.000000
licenses                   0         0.000000
cpe                        0         0.000000
locations                  0         0.000000
found_by                   0         0.000000
sbom_source                0         0.000000
analyzed_at                0         0.000000

================================================================================
NULL ANALYSIS: dependency_vulnerabilities
================================================================================

                         null_count  null_percentage
related_cve                     204        28.254848
epss                             62         8.587258
cvss_score                       12         1.662050
vulnerability_record_id           0         0.000000
package_name                      0         0.000000
repository_id                     0         0.000000
repository                        0         0.000000
dependency_id                     0         0.000000
language                          0         0.000000
package_type                      0         0.000000
package_version                   0         0.000000
purl                              0         0.000000
vulnerability_id                  0         0.000000
location                          0         0.000000
severity                          0         0.000000
risk                              0         0.000000
cwe                               0         0.000000
fix_state                         0         0.000000
fix_versions                      0         0.000000
description                       0         0.000000
data_source                       0         0.000000
namespace                         0         0.000000
tool                              0         0.000000
analyzed_at                       0         0.000000

In [41]:
critical_fields = {
    "codeql": [
        "repository",
        "severity",
        "rule_id",
        "file",
    ],
    "dependencies": [
        "repository",
        "package",
        "version",
    ],
    "dependency_vulnerabilities": [
        "repository",
        "package",
        "vulnerability_id",
        "severity",
    ],
}

for dataset_name, fields in critical_fields.items():
    df = datasets[dataset_name]

    print("=" * 80)
    print(f"CRITICAL FIELD VALIDATION: {dataset_name}")
    print("=" * 80)

    for field in fields:
        if field not in df.columns:
            print(f"[MISSING COLUMN] {field}")
            continue

        missing = df[field].isnull().sum()

        print(
            f"{field:<25} -> "
            f"missing: {missing:,} "
            f"({missing / len(df) * 100:.2f}%)"
        )

================================================================================
CRITICAL FIELD VALIDATION: codeql
================================================================================
[MISSING COLUMN] repository
severity                  -> missing: 0 (0.00%)
rule_id                   -> missing: 0 (0.00%)
[MISSING COLUMN] file
================================================================================
CRITICAL FIELD VALIDATION: dependencies
================================================================================
[MISSING COLUMN] repository
[MISSING COLUMN] package
[MISSING COLUMN] version
================================================================================
CRITICAL FIELD VALIDATION: dependency_vulnerabilities
================================================================================
repository                -> missing: 0 (0.00%)
[MISSING COLUMN] package
vulnerability_id          -> missing: 0 (0.00%)
severity                  -> missing: 0 (0.00%)